# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tijmen van Etten
title: Full-Stack AI Developer
email: tijmenettenvan@gmail.com
website: tijmenvanetten.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: tijmenvanetten
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: tijmen_vanetten
linkedin_username: tijmenvanetten
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Tijmen, a Full-Stack AI Developer with a passion for building intelligent systems. I have a strong background in Artificial Intelligence and extensive experience in developing and deploying AI solutions.

  Throughout my career, I have worked on various projects leveraging machine learning, deep learning, and natural language processing techniques. I am skilled in designing and implementing robust algorithms and models that drive actionable insights and enhance decision-making processes.

  I am highly motivated and dedicated to delivering high-quality results. I enjoy collaborating with cross-functional teams to tackle complex problems and contribute to innovative solutions. My strong analytical and problem-solving skills enable me to effectively identify and address challenges in AI development.

  When I'm not coding, you can find me exploring the latest advancements in AI research, honing my skills in competitive programming, or enjoying outdoor activities like hiking and cycling.

  Feel free to reach out to me if you have any questions or if you're interested in discussing potential collaborations. I'm always excited to explore new opportunities in the field of AI development.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: MyrmidonBot - Winning Entry Infosys Hackathon 2021
        link: https://github.com/tijmenvanetten/Myrmidon.git
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Myrmidon is a project that won the first prize in the InStepHacks Infosys Hackathon 2021. It introduces a modular approach to combining healthcare chatbot services in order to provide a seamless experience to patients. The project utilizes the Rasa Open Source framework and leverages custom actions to instantiate different chatbot models when triggered. The MyrmidonBot acts as a central hub, redirecting messages to the appropriate bots and maintaining a coherent conversation with the user. The aim of the project is to enhance the patient's interaction with chatbots by integrating multiple specialized bots into a unified system.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shell PLC
        link: shell.com
        sub_title: AI Research Intern - Decarbonisation Data Science
        caption: Jan 2023 - Current
        description: | # this will include new lines to allow paragraphs
          Developed a methodology to accurately predict electric vehicle charging load, enabling proactive planning and optimization of energy resources.
          Collaborated with stakeholders and communicated findings effectively, translating complex technical concepts into actionable recommendations for business units and project teams.

      - layout: left
        title: De Kleine Consultant
        link: dekleineconsultant.nl
        sub_title: Director, Strategy Consultant
        caption: Sept 2022 - Current
        description: | # this will include new lines to allow paragraphs
          Conducted comprehensive market research and analysis to identify opportunities and advice clients ranging from charities to large enterprises; built advanced excel models to create revenue projections.
          Oversaw and managed operations of a student-run non-profit strategy consulting firm of 25 consultants; led an initiative with external partners to sponsor students that are not in the financial situation to do work without compensation.
          Demonstrated strong analytical skills, attention to detail, and a strategic mindset in all aspects of project execution.

      - layout: left
        title: ABN AMRO
        link: abnamro.com
        sub_title: Data Science Intern
        caption: Jul 2022 - Aug 2022
        description: | # this will include new lines to allow paragraphs
          Utilized a combination of traditional and advanced machine learning techniques to create an intelligent system with reasonably accurate estimation of solar potential.
          Developed an AI system to automate the generation of personalized plans for installing solar panels; implemented the system in a real-time dashboard, allowing clients to receive personalized plans instantly.
      
      - layout: left
        title: University of Amsterdam
        link: uva.nl
        sub_title: Teaching Assistant in Linear Algebra and Webtechnologies & Databases
        caption: Jan 2022 - May 2022
        description: | # this will include new lines to allow paragraphs
          Guided group projects where students developed their own websites, providing guidance and expertise in web technologies and databases throughout the entire process.
          Assisted the professor in conducting tutorials, grading assignments and exams; provided guidance and support to undergraduate students in understanding and solving complex mathematical problems related to linear algebra.

      - layout: left
        title: Infosys Limited
        link: infosys.com
        sub_title: Software & ML Intern
        caption: May 2021 - August 2021
        description: | # this will include new lines to allow paragraphs
          Developed a Python module for PDF structure extraction, enabling the indexing of unstructured documents for efficient information retrieval; could be further used to generate supervised data in the COCO format used to fine-tune Computer Vision-based object detection models for scanned documents.
          Led a team as captain in the Infosys Hackathon, for which we developed and proposed a modular NLP system that combined multiple healthcare-related chatbots through APIs in a single user interface; won first prize out of 33 teams.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Amsterdam
        caption: Sept 2021 - Current
        sub_title: Master of Science in Artificial Intelligence
        description: | # this will include new lines to allow paragraphs
          - Relevant courses: Machine Learning, Deep Learning, Natural Language Processing, Computer Vision, Reinforcement Learning, Advanced Topics in Computational Semantics, Information Theory.
          - Thesis: Global Temporal Fusion Transformers for Enhancing Robustness in Forecasting Electric Vehicle Charging Load through Joint Time-Series Learning.
          > GPA: 8.3/10 (Cum Laude)

      - layout: left
        title: University of Amsterdam
        caption: Sept 2017 - Mar 2021
        sub_title: Bachelor of Science in Artificial Intelligence
        description: | # this will include new lines to allow paragraphs
          -  Minor: Applied Econometrics, Technical Track at the Vrije Universiteit Amsterdam
          - Thesis: End-to-end Open-Domain Question Answering using Neural Document Retrieval with Efficient Vector Representations and pre-trained Transformer Architecture for QA (Facebook AI Research) 8.0/10.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI development, I am also passionate about
      
  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      **Languages**
      - Python
      - C/C++
      - JavaScript
      - Matlab
      - Prolog
      - Clingo ASP

      **Libraries**
      - PyTorch
      - TensorFlow
      - Scikit-Learn
      - Transformers
      - Pandas
      - NumPy
      - Matplotlib
      - Seaborn

      **Miscellaneous**
      - MLOps
      - SQL
      - Git
      - Docker
      - PowerBI
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
